export let SET_ALL_POSSIBLE_COMBINATIONS = 'SET_ALL_POSSIBLE_COMBINATIONS';
export let SET_COMBINATION_AS_ACTIVE = 'SET_COMBINATION_AS_ACTIVE';
export let SET_PAYWAYS_FOR_COMBINATION = 'SET_PAYWAYS_FOR_COMBINATION';
export let SET_COMBINATION_LENGTH = 'SET_COMBINATION_LENGTH';
export let DISPLAY_GRID_FOR_PAYWAY = "DISPLAY_GRID_FOR_PAYWAY";
export let SET_GRID_FOR_PAYWAY = "SET_GRID_FOR_PAYWAY";
export let SET_ACTIVE_ICON_INDEX = "SET_ACTIVE_ICON_INDEX";
