export let SET_ALL_POSSIBLE_COMBINATIONS = 'SET_ALL_POSSIBLE_COMBINATIONS';
export let SET_COMBINATION_AS_ACTIVE = 'SET_COMBINATION_AS_ACTIVE';
export let SET_PAYWAYS_FOR_COMBINATION = 'SET_PAYWAYS_FOR_COMBINATION';
export let SET_COMBINATION_LENGTH = 'SET_COMBINATION_LENGTH';
